[package]
name = "Silicon_Chess"
version = "0.0.0"
authors = ["simonk <simonkotchou@mines.edu>"]
license = "MIT"
edition = "2018"

[dependencies]
rayon = "1.5.1"
tch = "0.6.0"

[dev-dependencies]
criterion = "0.3"